---
title: "HW 5 solutions"
author: "Mike Lopez"
date: "September 2017"
output:
  html_document
---

```{r global_options, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(dplyr)
library(ggplot2)
```

***General instructions for homeworks***: 

+  Make a new R Markdown file (.Rmd) referring to thea assignment on the course Github page
+  Change the heading to include your author name
+  Save the R Markdown file (named as:  [MikeID]-[Homework01].Rmd -- e.g. "mlopez-Lab01.Rmd") to somewhere where you'll be able to access it later (zip drive, My Documents, Dropbox, etc)
+  Your file should contain the code/commands to answer each question in its own code block, which will also produce plots that will be automatically embedded in the output file
+  **Each answer must be supported by written statements (unless otherwise specified) as well as any code used**: In other words, if the answer is `24`, you should write "The answer is 24" (as opposed to just showing the code and output).
+  Include the names of anyone you collaborated with at the top of the assignment

### Part I: 

Open Intro: 2.15, 2.16, 2.17, 2.20, 2.24, 2.32, 2.33, 2.34, 2.35, 2.36

**2.16**

a. 0.871

b. 0.571

c. About 0

d. 0.69-0.31 = 0.38



**2.24**


a. In code: pnorm(48, 55, 6) = 0.12  (about 12 percent).

Using z-scores, z = (48-55)/6 =  -1.17, pnorm(-1.17) = 0.12

Either way is fine

b. In code: pnorm(65, 55, 6) - pnorm(60, 55, 6) = 0.15 (about 15 percent)

Using z-scores, the z-score for 65 is 1.66 and the z-score for 60 is 0.83

pnorm(1.66) – pnorm(0.83) = 0.15


c. qnorm(0.9) = 1.28

X = 1.28*6 +55 = 62.68 (the cutoff is about 62.7 inches)


d. In code: pnorm(54, 55, 6) = 0.43 (about 43 percent)

Using z-scores: z = (54-55)/6 = -0.166

pnorm(-0.166) = 0.43

Either way is fine


2.32

68% interval: (56.9, 66.1). 15 of the 25 subjects, or 60%, fall in this interval. We expect 68%, so this is very close. 

95% interval: (52.3, 70.7). 24 of the 25 subjects, or 96%, fall in this interval. We expect 95%, so this is very close. 

All subjects fall within three standard deviations of the mean. As a result, we can conclude that heights approximately follow the 68-95-99.7 rule 





## Part II: Gender discrimination in the workplace? 

Use the `profiles` data set from the `okcupiddata` package. 

1. Drop any observation with height less than 50 or greater than 90, and save this as a new data frame, `profiles1`. 

2. Using your new data set, identify if the distribution of heights is normally distributed by using (i) a histogram and (ii) a qq plot.

3. Repeat (1), only using a separate analysis for each gender. Do your conclusions match? 